### ISSUE TITLE
Clarification on saving the game

### ISSUE THREAD

**Issue by kerrywatson1** [ContinuumIO/ui-coding-challenge#5]
Do you want the user to explicitly save the game each time, or should we take care of this in the background for them when a game is created / updated? 

I'll add the answer to the README.

**Comment by kerrywatson1** [comment]
@necaris FYI @canaandavis

**Comment by necaris** [comment]
@kerrywatson1 I think this is something we want to leave up to the developer -- I don't think either is unacceptable, and it's interesting to see and discuss why an option was chosen. I would encourage a developer to go with the direction they're leaning in.

/cc @canaandavis

**Comment by kerrywatson1** [comment]
Cool, closing issue.
